/*
https://leetcode.com/problems/find-the-difference/description/

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

package main

func findTheDifference(s string, t string) byte {
  arr1 := make([]int, 26)
  arr2 := make([]int, 26)

  for _, c := range s {
    arr1[int(c-'a')]++
  }
  for _, c := range t {
    arr2[int(c-'a')]++
  }

  for i, count := range arr1 {
    if count < arr2[i] {
      return byte('a' + i)
    }
  }
  return 0
}

func main() {

}
